# Site settings
title: yujiange
email: yujiange@gmail.com
author: yujiange
description: "yujiange"
baseurl: ""
url: "http://yujiange.github.io"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
